# Generated by Django 4.0.2 on 2022-03-28 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_variant', '0001_initial'),
        ('product_subtype', '0001_initial'),
        ('product_category', '0001_initial'),
        ('product_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('tags', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_category.category')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_variant.variant')),
                ('subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_subtype.subtype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_type.type')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'managed': True,
            },
        ),
    ]
