# Generated by Django 4.0.2 on 2022-03-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=100)),
                ('invoice_id', models.CharField(blank=True, max_length=100)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('invoice_url', models.CharField(blank=True, max_length=100)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.CharField(blank=True, max_length=100)),
                ('delivery_address', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
